# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 366c3b0b12e7e7dcd67172ee054b7ab67bd9a09a884f9d66f4995540594b442f11623624daf09887c505f350aa8505fc14cb37520f1a450d5097a19b5808eb83

test:
  secret_key_base: cd1a155f2f2f395c11832085ab6a649cb325274149c78eb4db2c9d096f54f6d02405b3cec8e9323d783cbd3b8b40218204cfbcdf5219a2f34587eed38ce80443

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
